### ISSUE TITLE
Obtain Production Servers

### ISSUE THREAD

**Issue by danfunk** [sartography/star-drive#10]
Work with ITS to provide us with the necessary server infrastructure to support this project.

- [x] Establish a server on the DMZ for hosting the public facing mirror.
- [x] Establish a server on the private network, behind the Joint VPN for administrative access.
- [ ] Assure database backups are in place for both servers.
- [x] Obtain a domain name, registered through UVA and attach it to the public mirror.
- [ ] Test connections between the servers.

**Comment by calexh-sar** [comment]
Dan, moving this ticket to "In Progress" since I remember you mentioning that you have done some/all of this ticket.  Pls move it further down the line if have completed this work, or check off the items done in the description.  Thx!

**Comment by calexh-sar** [comment]
Closing per discussion with Dan.
