### ISSUE TITLE
Locations with no street address

### ISSUE THREAD

**Issue by eleanorgraham** [sartography/star-drive#146]
Map location based on zip code, with alternate treatment for map point. See feedback document, slides [37](https://docs.google.com/presentation/d/1m49n2CCNruc80vFHFpLImbCrogKH0l9nIk0Zaj6f6J4/edit?pli=1#slide=id.g60a354c889_0_232)-[38](https://docs.google.com/presentation/d/1m49n2CCNruc80vFHFpLImbCrogKH0l9nIk0Zaj6f6J4/edit?pli=1#slide=id.g60a354c889_0_245) for details.

**Comment by calexh-sar** [comment]
Currently slides [24](https://docs.google.com/presentation/d/1m49n2CCNruc80vFHFpLImbCrogKH0l9nIk0Zaj6f6J4/edit?pli=1#slide=id.g5f08046ee1_0_13) & [25](https://docs.google.com/presentation/d/1m49n2CCNruc80vFHFpLImbCrogKH0l9nIk0Zaj6f6J4/edit?pli=1#slide=id.g5f08046ee1_0_65)
