### ISSUE TITLE
Home page update - 09/03 Feedback

### ISSUE THREAD

**Issue by calexh-sar** [sartography/star-drive#193]
From (current) [slide 3 of Feedback deck](https://docs.google.com/presentation/d/1m49n2CCNruc80vFHFpLImbCrogKH0l9nIk0Zaj6f6J4/edit?pli=1#slide=id.g60766af878_0_13):

Remove “autism” from “Transform autism outcomes. Together.”

**Comment by eleanorgraham** [comment]
Fixed in PR #185
