### ISSUE TITLE
Find Support: Disable mouse zoom of Google map

### ISSUE THREAD

**Issue by calexh-sar** [sartography/star-drive#212]
Since the Google map takes up a fair portion of the main Find Support page, I often inadvertently place my mouse in that area when attempting to scroll down the page to see the listed resources.  From the perspective of this user only at this point, I would prefer if the mouse zoom in/out function be disabled and the user would need to use the + & - menu option to do so.  Clicking on numbered circles and such should still zoom as usual.

**Comment by calexh-sar** [comment]
Also noted on [slide 84 in the 09/17/2019 section of the feedback deck](https://docs.google.com/presentation/d/1m49n2CCNruc80vFHFpLImbCrogKH0l9nIk0Zaj6f6J4/edit?pli=1#slide=id.g60b626d0dd_1_37):

Whenever you’re scroll down a page that has the map, it often accidentally zooms in and out on the map which can be a little annoying. Not sure if there would be anything to help that.

**Comment by ajlouie** [comment]
Some info on how to tell agm to ignore the scroll gesture: https://github.com/SebastianM/angular-google-maps/issues/1411
