### ISSUE TITLE
Google Analytics for Related Resources & Research Studies

### ISSUE THREAD

**Issue by calexh-sar** [sartography/star-drive#234]
During the 09/24 weekly feedback meeting, Rose and Micah requested that Google Analytics be added to the Related Resources and Research Studies links on the individual Study page to better understand if users are clicking those links.

**Comment by calexh-sar** [comment]
Should discuss immediate metrics and time for future additions.

**Comment by eleanorgraham** [comment]
While I'm at it, I think I'll add in tracking for the related topics clicks.
