### ISSUE TITLE
All of the study status labels start with word “Config”

### ISSUE THREAD

**Issue by calexh-sar** [sartography/star-drive#252]
From [slide 93 in Feedback deck](https://docs.google.com/presentation/d/1m49n2CCNruc80vFHFpLImbCrogKH0l9nIk0Zaj6f6J4/edit?pli=1#slide=id.g6204b0cbfd_0_5).  Appears it may already be fixed on staging, adding this ticket to track progress on deck.

**Comment by eleanorgraham** [comment]
Fixed in PR #248
