### ISSUE TITLE
Review/edit draft text for DRIVE pages

### ISSUE THREAD

**Issue by mm5gt** [sartography/star-drive#27]
I have just uploaded the draft text/layout we reviewed today that should correspond to the staging site.  Feel free to edit and revise.  The link to google drive is below:
[https://drive.google.com/drive/u/1/folders/17ZMC1kO5mQQSXpORSmv8Nka4Vf0G8arZ](url)

**Comment by Rose-Nevill** [comment]
A larger pdf version of the region breakdown included in this document has also been added: STAR DRIVE --> Virginia Region Map.pdf

**Comment by mm5gt** [comment]
Yay!  our first GitHub post!

**Comment by ajlouie** [comment]
Closing this issue, since we have other tickets for finalized site text and updated resources.
