### ISSUE TITLE
Additional System Emails

### ISSUE THREAD

**Issue by calexh-sar** [sartography/star-drive#285]
In the 11/05 weekly meeting, the Star team mentioned they would like to add additional system emails which are sent based on specified criteria.  This ticket is a placeholder to be completed once the team provides additional details on which emails and what criteria.

**Comment by eleanorgraham** [comment]
First step: 
- emails to users with 0 participants (created an account, but haven't filled out any enrollment info)
- emails to guardian users with 0 dependents
