### ISSUE TITLE
Post-Launch Search/Map Refinements

### ISSUE THREAD

**Issue by calexh-sar** [sartography/star-drive#286]
### Topics Navigation
- [x] Usability and visual design of Topic/Subtopic filter is confusing. The resources have all been organized according to the taxonomy, and the search results don't really expose the structure of the topics/subtopics to make them discoverable. 
- [x] Display nested topics in autocomplete suggestions
- [x] Don't truncate topic/subtopic names (Replace menu with expandable section?)
- [x] Show autocomplete suggestions on focus in search box

### Guidance text & video
- [x] Add help text next to H1 explaining what to do with search ("Type a search term or select a resources catetgory") once the search box to-do items above are fixed.
- [x] Put search tutorial video somewhere on the search screen
- [x] Keep search filters with search box
- [x] Button to hide video
- [x] Guidance text with video "Watch this video for guidance on selecting resources. . 
For more information on evidence-based resources, check out resources from the [National Autism Center](url) and the [Frank Porter Graham Child Development Institute](url)."

**Comment by ajlouie** [comment]
Mobile usability problems on Samsung Galaxy S8. Map is not appearing.

Results and filters are not updating properly. Searching with a keyword doesn't update the search results.
