### ISSUE TITLE
Export All option

### ISSUE THREAD

**Issue by calexh-sar** [sartography/star-drive#316]
Placeholder ticket for enhancement request made during 12/17/2019 weekly meeting.  Additional details may be found on [slide 156](https://docs.google.com/presentation/d/1m49n2CCNruc80vFHFpLImbCrogKH0l9nIk0Zaj6f6J4/edit?pli=1#slide=id.g75fe52bbb7_0_59) of the Feedback Deck.

**Comment by eleanorgraham** [comment]
Duplicate of #295
