### ISSUE TITLE
Resource search UX

### ISSUE THREAD

**Issue by eleanorgraham** [sartography/star-drive#345]
The team is gathering feedback about how the resource search page functions and will be asking for multiple updates. This is a placeholder for now to estimate that effort, although it still needs more definition

**Comment by eleanorgraham** [comment]
Issues #357  #369  #373 are all related to and/or part of this ticket. Once we test those fixes with the team and users we will revisit this ticket and decide if more is needed. For now, however, it will sink down to a lower priority for a while.

**Comment by ajlouie** [comment]
- [ ] Map is covering up results list on small screens
- [ ] Filters and type selector are aligned strangely on small screens
