### ISSUE TITLE
Form Validation - Front end

### ISSUE THREAD

**Issue by danfunk** [sartography/star-drive#47]
Assure proper form validation on the front end.  We just need to go over every field and make sure reasonable checks are in place.   Just a few things I noticed while testing that should get fixed:

- [ ] State field in address should be a drop down or provide text validation.
- [x] Age field should require a reasonable value, nothing in the 1000's for instance.

**Comment by ajlouie** [comment]
Closing, since most form validation issues have been fixed. State validation will be opened as a separate post-launch issue.
