### ISSUE TITLE
Add new study pic

### ISSUE THREAD

**Issue by eleanorgraham** [sartography/star-drive#479]
We need another new picture for the studies. It would be lovely to give the team the ability to add/manage these themselves

**Comment by wendyhan2016** [comment]
The new image is not applied on production site.

**Comment by ajlouie** [comment]
Image was already added to the codebase. Just needed to be edited in the study form.

**Comment by ajlouie** [comment]
For future reference, any image in the assets directory can be used for study images:
https://github.com/sartography/star-drive/tree/master/frontend/src/assets/home
