### ISSUE TITLE
Event Resource Details enhancements

### ISSUE THREAD

**Issue by ajlouie** [sartography/star-drive#485]
By 10/2/2020

Edit form for Event
- [x] Add hero image
- [x] Add registration call-to-action button
- [x] Option to hide related resources

**Comment by wendyhan2016** [comment]
- The draft of the landing page: https://autismdrive.virginia.edu/#/event/4127
- image for the banner 

![1](https://user-images.githubusercontent.com/57197630/94946181-bd7cf800-04a9-11eb-9345-dd04f0de5a93.png)

[](url)
