### ISSUE TITLE
Search FrontEnd / User Interface

### ISSUE THREAD

**Issue by danfunk** [sartography/star-drive#49]
We need a search box on the front end for searching Current Studies, Training, and Resources.  A top level search across both Studies and Training should be possible.  As well as restricted searches against each.

**Comment by eleanorgraham** [comment]
Addressed in PR #83 
We still need the restricted searches or a clarification of the Studies and Trainings/Resources pages

**Comment by eleanorgraham** [comment]
Closing this, as search filters already include a restricted search, and we are in the process of redesigning/rethinking the function of the Current Studies and Training/Resources pages.
