### ISSUE TITLE
Improve loading speed of studies. Reduce overall size of payload.

### ISSUE THREAD

**Issue by ajlouie** [sartography/star-drive#493]
- [x] Move images into curry.virginia.edu content management system to reduce size of payload.
- [x] Find out why the [currently_enrolling endpoint response](https://autismdrive.virginia.edu/api/study/status/currently_enrolling) is 1.3MB on production.

**Comment by ajlouie** [comment]
Fixed by #494

**Comment by calexh-sar** [comment]
@ajlouie would you please add t-shirt estimate and type labels to this ticket.

**Comment by ajlouie** [comment]
Once images have been moved into the CMS, we'll remove the images from the assets directory.
