### ISSUE TITLE
Improved Study Enrollment Process Display / Flow

### ISSUE THREAD

**Issue by danfunk** [sartography/star-drive#50]
We need to design and implement a process for signing up for Studies.  Not sure how this wlll work, may require some additional details.  (Assigning Rose to this in case she can help us work through this flow).  What happens exactly when someone is viewing a study and selects "Enroll in this Study".  I suspect it will be different for each study, but all studies may not have a website or form where users can sign up.

**Comment by Rose-Nevill** [comment]
Is this possible: we enter an email for the lab/PI, and have an auto email generated to that lab/PI when someone clicks "enroll". To keep it de-identified, perhaps we could send a database registry number - "Participant 459 is interested in this study, please contact them to follow up," at which point it will be up to the researcher on the receiving end to log on and access that participant's contact info. From the user side, they click enroll now, and a message appears "thanks! A researcher from this study's research team will contact you using the time and method you indicated as preferred when you completed the registration process" or something along those lines.  

Or: upon clicking "enroll now", they are shown a small form to indicate how and what time they'd like to be contacted by the research team- this info is then sent to the researcher. But we will already have preferred way and time to contact collected as part of the registration process, so it seems redundant to collect this info a second time. 

Let me know what you think about these.

**Comment by eleanorgraham** [comment]
We talked about this flow at the 6/4/19 meeting and agreed on creating some version where a user can indicate interest for a particular participant in a study, and this indication generates an email to the PI. We could also send an email and/or display a message to the user that explains that the PI will be following up to determine eligibility etc.

**Comment by eleanorgraham** [comment]
The Enroll button on study should be revisited --
When there is no user, prompt to sign in or sign up
When there is a user, prompt to indicate interest for participant (gray out participants with incomplete enrollment/registration information)

**Comment by eleanorgraham** [comment]
- [ ] Add study coordinator contact field to study
- [ ] Retrieve appropriate contact information for user/participant
- [ ] Create email templates for Study Coordinator and Participant/User
- [ ] User-aware buttons on study detail page (signed out, signed in - registration incomplete, signed in - registration complete)
- [ ] Pop-up for participant selection
