### ISSUE TITLE
Irmpoved Landing / Home Page

### ISSUE THREAD

**Issue by danfunk** [sartography/star-drive#51]
This may need to wait on other aspects of the site being completed.  Particularly a strong search page.  This landing page should have clear and immediate calls to action, along with brief descriptions of why someone would want to continue.    I think having UVA as a part of a whiteboard discussion with Aaron might help greatly in the matter, or perhaps a fresh proposal from Aaron on how to pull this together.  And of course we need to finalize images.

**Comment by eleanorgraham** [comment]
We have a new design approved by the team and ready to implement - this includes highlighting currently enrolling studies, as well as a link to the full studies page.

**Comment by eleanorgraham** [comment]
Fixed in PR #140
