### ISSUE TITLE
Location Aware Resources - Map Interface

### ISSUE THREAD

**Issue by danfunk** [sartography/star-drive#53]
Some, but not all, Resources will be offered at a certain location.  We need to include the ability to associate hard locations about a resource and incorporate this into a map interface that allows users to easily see resources that are near them.  

**A few things this ticket should not cover:**

-  Searching based on location.  I suggest we offer a map only.  The search interface would become convluted with contrary options because not all resources have locations, and some resources may be offered in many different locations.  A map would convey this aspect clearly and concisely.  
- For our initial effort, a location is a fixed point with no diameter.  A local class might have a small audience, but a conference might cover a larger area.  We won't try to handle this in the first release.

**Comment by eleanorgraham** [comment]
Feature added in PR #124 - Awesome work, @ajlouie :star: 

We do plan to tackle the issue of locations without set street addresses before launch as a separate issue.
