### ISSUE TITLE
Search - Backend

### ISSUE THREAD

**Issue by danfunk** [sartography/star-drive#56]
We have ElasticSearch in place and populating.  We just need to make sure we have sensible data structures and endpoints in place for performing faceted searches across the collection of resources and studies.  While this should not include location based searches (unless we change our minds), it should include a robust ability to find resources/studies/training that meet criteria that a participant might be interested in.  We can re-use this feature to provide suggestions for participants.

**Comment by eleanorgraham** [comment]
Added in PR #83
