### ISSUE TITLE
Self-Registration edits

### ISSUE THREAD

**Issue by Rose-Nevill** [sartography/star-drive#81]
The updated Self-registry looks great! A few minor issues still found:

Evaluation History
o	IQ score question:  It doesn’t allow you to type in an answer
o	Save and Next button – page not responding 
Clinical Diagnoses
o	Please change Insomnia to “Insomnia (problems falling or staying asleep) or other sleep problems”
Supports
o	Under Type of therapy or service, it’s not clear what should be written in the “Description” box if you select an item from the drop down menu other than “Other”, and then what should go into the “notes on use” box below – should the Description box only be appearing when Other is selected? 
o	AAC question: please include list of AAC Devices – current list only refers to adaptive equipment.
	Sorry I didn’t provide a list of AAC devices sooner. Here is one:
•	Paper and pen(cil)
•	Gestures, pointing, and body language
•	American Sign Language (ASL)
•	Picture icons
•	Speech output buttons (e.g., BIGmack)
•	High tech device (e.g., tablet, Dynavox, Proloquo2Go)

**Comment by eleanorgraham** [comment]
From Rose, regarding AAC:

> Here’s what we’ve come up with based on text from the American Speech and Hearing Association:
> 
> No-Tech AAC: facial expressions, body posture, head nods, reaching/pointing, gestures, and signs.
> 
> Low-Tech AAC: pen and paper, pictures/symbols, communication boards, and communication books. 
> 
> Mid -Tech AAC: battery operated or simple electronic devices. 
> 
> High-Tech AAC: dynamic, computerized display devices such as tablets and ipads containing pages of letters, words, pictures, or symbols
> 
> I think some of these (esp the last line) may be too long to fit all the text on one line, so feel free to shorten as you feel fit.

**Comment by Rose-Nevill** [comment]
Hi Eleanor,

Thanks for sending. I made edits below to try to shorten!

Rose

**Comment by eleanorgraham** [comment]
Lovely -- thank you. I'll see what this looks like in context and hopefully have a version in the next update for you.

**Comment by eleanorgraham** [comment]
Fixed by PR #91
